### Register a new user
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "username": "john_doe",
  "email": "john.doe@example.com",
  "password": "securePassword123",
  "weight": 85,
  "firstName": "John",
  "lastName": "Doe"
}

### Login with username or email
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "emailOrUsername": "john.doe@example.com",
  "password": "securePassword123"
}


### Add a result for a user
POST http://localhost:3000/api/users/addResult
Content-Type: application/json
Authorization: Bearer b3f3b600f436a952c0195e907d30f5512c50d75321290db8ecd96f65921498f1

{
  "userId": "67c4372abd080bcbad4987de",
  "weight": 90,
  "powerliftingSumWeight": 250,
  "points": 1200
}